name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to AWS ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 173174563721.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker Image
      run: docker build -t my-node-app .

    - name: Tag Docker Image
      run: docker tag my-node-app:latest 173174563721.dkr.ecr.us-east-1.amazonaws.com/my-node-app-repo:latest

    - name: Push Docker Image
      run: docker push 173174563721.dkr.ecr.us-east-1.amazonaws.com/my-node-app-repo:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster my-node-app-cluster \
          --service my-node-app-service \
          --force-new-deployment
